// Cloudflare Workers entry for the PerryLink DSH Catalog standard source.
// Serves /catalog-source.json and /v1/plugins as application/json, plus
// /icons/*.png (same-origin plugin icons, per the market media rule) from
// the base64 map generated by scripts/build-icons.mjs. The deploy/ folder
// is self-contained: build-catalog.mjs mirrors the JSON artifacts into it.
import manifest from './catalog-source.json' with { type: 'json' }
import page from './artifacts/v1/plugins.json' with { type: 'json' }
import { icons } from './icons-data.mjs'

const text = (payload) => new Response(JSON.stringify(payload), {
  headers: { 'content-type': 'application/json; charset=utf-8', 'access-control-allow-origin': '*' },
})

export default {
  async fetch(request) {
    const { pathname } = new URL(request.url)
    if (request.method !== 'GET') return new Response('method not allowed', { status: 405 })
    if (pathname === '/catalog-source.json') return text(manifest)
    if (pathname === '/v1/plugins') return text(page)
    const b64 = icons[pathname]
    if (b64) {
      const bytes = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0))
      return new Response(bytes, {
        headers: { 'content-type': 'image/png', 'cache-control': 'public, max-age=86400' },
      })
    }
    return new Response('not found', { status: 404 })
  },
}
